server:
  mode: debug  # debug, release, test
  http_port: 9876
  rpc_port: 9090
  read_timeout: 60000  # 毫秒
  write_timeout: 60000 # 毫秒
  jwt_secret: "your-secret-key-change-in-production"  # JWT密钥
  external_url: "http://10.122.28.13:5173"  # 外部访问URL，用于OAuth2 SSO，如 http://10.122.24.67:9876
  frontend_url: ""  # 前端URL，用于OAuth2登录重定向，本地开发默认 http://localhost:5173

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: opshub
  username: root
  password: "DUjie123!"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # 秒

redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 0
  pool_size: 10
  min_idle_conn: 5

log:
  level: info  # debug, info, warn, error
  filename: logs/app.log
  max_size: 100      # MB
  max_backups: 10
  max_age: 30        # days
  compress: true
  console: true
